(* This file is automatically generated *)

let datadir,
  localedir,
  charmapdir,
  unimapdir = 
  let (//) = Filename.concat in
  let data_root = "/usr/local/share" // "camomile" in
  data_root // "database", 
  data_root // "locales",
  data_root // "charmaps",
  data_root // "mappings"
